#!/bin/sh
# rc  This file is responsible for starting/stopping services
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
# Call function
. /etc/init.d/vstfunc
if [ -f /etc/init.d/p2pset.sh ]; then
	/etc/init.d/p2pset.sh &
fi

# swap
#echo "init swap"
#/etc/init.d/swap > /dev/null 2>&1
#start udev
#modify by zhangwei 20130722
/etc/init.d/udev  > /dev/null 2>&1
# Check rc directory for runlevel
[ -d /etc/rc.d/rc1.d ] || exit 0
# Run the START scripts.

[ -f /lib/modules/sch_sqos.ko ] && insmod /lib/modules/sch_sqos.ko

for i in /etc/rc.d/rc1.d/S* ; do
	# Check if the subsystem is already up.
	Stmp=`echo $i | grep S32smbd`
	if [ ! -z $Stmp ]; then
	continue;
	fi
	subsys=${i#/etc/rc.d/rc1.d/S??}
	if [ -f /var/run/$subsys.pid ];then
		echo $i restart
		$i restart
		continue
	fi
	# Bring the subsystem up.
	echo $i start
	$i restart
done

#Modify for 3G reset not Open
if [ ! -f /etc/checktelnetflag ]; then
	telnetd &
elif [ -f /etc/telnetflag ]; then
	telnetd &
fi
if [ -f /etc/update/update.cfg ]; then
	/usr/sbin/au &
fi
# Set 
#echo "STARTUP=0" > /tmp/startupflag

#Set network parameters
#echo 256960 > /proc/sys/net/core/rmem_default
#echo 256960 > /proc/sys/net/core/rmem_max
#echo 256960 > /proc/sys/net/core/wmem_default
#echo 256960 > /proc/sys/net/core/wmem_max
#echo 0 > /proc/sys/net/ipv4/tcp_timestamps
#echo 1 > /proc/sys/net/ipv4/tcp_sack
#echo 1 > /proc/sys/net/ipv4/tcp_window_scaling

#echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse
#echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle
#echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout
#echo "1200" > /proc/sys/net/ipv4/tcp_keepalive_time
 
#echo "4096 87380 8388608" > /proc/sys/net/ipv4/tcp_wmem
#echo "4096 87380 8388608" > /proc/sys/net/ipv4/tcp_rmem
 
#echo "4096" > /proc/sys/net/ipv4/tcp_max_syn_backlog
 
#echo 1 > /proc/sys/net/ipv4/conf/lo/rp_filter
#echo 1 > /proc/sys/net/ipv4/conf/eth0/rp_filter
#echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
#echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter

#Add by ljd
init_min_free_mem(){
        MEM_TOTAL=`grep MemTotal /proc/meminfo | awk '{print $2}'`
        if [ $MEM_TOTAL -gt 50000 ]; then
                MFREEMEM=8192
        else
                MFREEMEM=1024
        fi
        echo $MFREEMEM > /proc/sys/vm/min_free_kbytes
}

init_min_free_mem
if [ -f /usr/sbin/advertisement ]; then
	id=`pidof advertisement`
	[ -n "$id" ] && killall -KILL advertisement
	/usr/sbin/advertisement &
fi

if [ -f /usr/sbin/usbdongled ]; then
	usbdongled &
fi

#if [ -f /usr/sbin/listen_sleep.sh ]; then
#	/usr/sbin/listen_sleep.sh &
#fi

#/etc/init.d/listen_sleep.sh &
#cp /etc/udev/script/add_usb.sh /var/tmp/
#/etc/init.d/minidlna.sh start
echo "/usr/sbin/listen_sleep &"
/usr/sbin/listen_sleep &
if [ -f /usr/sbin/wificheck ]; then
	/usr/sbin/wificheck
fi
echo "STARTUP=0" > /tmp/startupflag
systime=`date +%s`
echo $systime > /tmp/systime
touch /tmp/rcend
#if [ -f usr/sbin/mipsp2p ]; then
#	POWER7TAIL=`cat /tmp/upnpd.conf |grep uuid | awk -F '=' '{print $2}'`
#	ACOUNT=POWER7_$POWER7TAIL
#	usr/sbin/mipsp2p  $ACOUNT 11111111 POWER7_2011 AAAAAA
#fi
exit
